const projects = [
  // =========================
  // Beginner Projects
  // =========================
  {
    id: 1,
    title: "Age Calculator",
    category: "Beginner",
    difficulty: "Easy",
    duration: "30 Min",
    image: "/images/age-calculator.png",
    description: "Calculate age using date of birth.",
    technologies: ["JavaScript", "HTML", "CSS"],
    status: "Free",
  },
  {
    id: 2,
    title: "BMI Calculator",
    category: "Beginner",
    difficulty: "Easy",
    duration: "30 Min",
    image: "/images/bmi.png",
    description: "Calculate body mass index.",
    technologies: ["JavaScript", "HTML", "CSS"],
    status: "Free",
  },
  {
    id: 3,
    title: "Digital Clock",
    category: "Beginner",
    difficulty: "Easy",
    duration: "40 Min",
    image: "/images/clock.png",
    description: "Live digital clock using JavaScript.",
    technologies: ["JavaScript"],
    status: "Free",
  },
  {
    id: 4,
    title: "Calculator",
    category: "Beginner",
    difficulty: "Easy",
    duration: "1 Hour",
    image: "/images/calculator.png",
    description: "Basic calculator application.",
    technologies: ["JavaScript"],
    status: "Free",
  },
  {
    id: 5,
    title: "Random Password Generator",
    category: "Beginner",
    difficulty: "Easy",
    duration: "45 Min",
    image: "/images/password.png",
    description: "Generate secure random passwords.",
    technologies: ["JavaScript"],
    status: "Free",
  },

  // =========================
  // Intermediate Projects
  // =========================
  {
    id: 6,
    title: "Weather App",
    category: "Intermediate",
    difficulty: "Medium",
    duration: "2 Hours",
    image: "/images/weather.png",
    description: "Fetch weather using an API.",
    technologies: ["JavaScript", "Fetch API"],
    status: "Free",
  },
  {
    id: 7,
    title: "To-Do App",
    category: "Intermediate",
    difficulty: "Medium",
    duration: "2 Hours",
    image: "/images/todo.png",
    description: "Manage daily tasks with LocalStorage.",
    technologies: ["JavaScript", "LocalStorage"],
    status: "Free",
  },
  {
    id: 8,
    title: "Notes App",
    category: "Intermediate",
    difficulty: "Medium",
    duration: "2 Hours",
    image: "/images/notes.png",
    description: "Create and save notes locally.",
    technologies: ["JavaScript", "LocalStorage"],
    status: "Free",
  },
  {
    id: 9,
    title: "Quiz App",
    category: "Intermediate",
    difficulty: "Medium",
    duration: "3 Hours",
    image: "/images/quiz.png",
    description: "Interactive MCQ quiz application.",
    technologies: ["JavaScript"],
    status: "Free",
  },
  {
    id: 10,
    title: "Expense Tracker",
    category: "Intermediate",
    difficulty: "Medium",
    duration: "3 Hours",
    image: "/images/expense.png",
    description: "Track income and expenses.",
    technologies: ["JavaScript", "Charts"],
    status: "Free",
  },

  // =========================
  // Advanced Projects
  // =========================
  {
    id: 11,
    title: "Movie Search App",
    category: "Advanced",
    difficulty: "Hard",
    duration: "4 Hours",
    image: "/images/movie.png",
    description: "Search movies using an API.",
    technologies: ["JavaScript", "Fetch API"],
    status: "Premium",
  },
  {
    id: 12,
    title: "GitHub Profile Finder",
    category: "Advanced",
    difficulty: "Hard",
    duration: "4 Hours",
    image: "/images/github.png",
    description: "Find GitHub users using GitHub API.",
    technologies: ["JavaScript", "REST API"],
    status: "Premium",
  },
  {
    id: 13,
    title: "E-Commerce Cart",
    category: "Advanced",
    difficulty: "Hard",
    duration: "5 Hours",
    image: "/images/cart.png",
    description: "Shopping cart with product management.",
    technologies: ["JavaScript", "LocalStorage"],
    status: "Premium",
  },
  {
    id: 14,
    title: "Banking Dashboard",
    category: "Advanced",
    difficulty: "Hard",
    duration: "5 Hours",
    image: "/images/bank.png",
    description: "Deposit, withdraw and transaction history.",
    technologies: ["JavaScript"],
    status: "Premium",
  },
  {
    id: 15,
    title: "Admin Dashboard",
    category: "Advanced",
    difficulty: "Hard",
    duration: "6 Hours",
    image: "/images/dashboard.png",
    description: "Responsive analytics dashboard.",
    technologies: ["JavaScript", "Charts"],
    status: "Premium",
  },
];

export default projects;