
const codingTasks = [
  {
    id: "e1",
    title: "Reverse a String",
    topic: "Strings",
    level: "Beginner",
    difficulty: "Easy",
    xp: 20,
    premium: false,
    description:
      "Write a function that takes a string and returns it reversed, without using the built-in .reverse() array method as a shortcut on the whole string (you may still use it internally if you split first).",
    examples: [
      { input: `"hello"`, output: `"olleh"` },
      { input: `"JavaScript"`, output: `"tpircSavaJ"` },
    ],
    constraints: ["1 <= s.length <= 10^4", "s consists of printable ASCII characters"],
    functionName: "reverseString",
    starterCode: `function reverseString(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["hello"], expected: "olleh" },
      { args: ["JavaScript"], expected: "tpircSavaJ" },
      { args: [""], expected: "" },
      { args: ["a"], expected: "a" },
    ],
    solution: `function reverseString(s) {\n  return s.split("").reverse().join("");\n}`,
    explanation:
      "Split the string into a character array, reverse the array in place, then join it back into a string. Time complexity O(n).",
  },
  {
    id: "e2",
    title: "Find the Largest Number",
    topic: "Arrays",
    level: "Beginner",
    difficulty: "Easy",
    xp: 20,
    premium: false,
    description:
      "Given an array of integers, return the largest number in the array. Do not use Math.max(...arr) — implement the comparison yourself.",
    examples: [
      { input: "[3, 7, 2, 9, 4]", output: "9" },
      { input: "[-5, -1, -10]", output: "-1" },
    ],
    constraints: ["1 <= arr.length <= 10^5"],
    functionName: "findLargest",
    starterCode: `function findLargest(arr) {\n  // your code here\n}`,
    testCases: [
      { args: [[3, 7, 2, 9, 4]], expected: 9 },
      { args: [[-5, -1, -10]], expected: -1 },
      { args: [[1]], expected: 1 },
      { args: [[5, 5, 5]], expected: 5 },
    ],
    solution: `function findLargest(arr) {\n  let max = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] > max) max = arr[i];\n  }\n  return max;\n}`,
    explanation:
      "Track the largest value seen so far starting from the first element, and update it whenever a bigger value is found. Single pass, O(n).",
  },
  {
    id: "e3",
    title: "Check for Palindrome",
    topic: "Strings",
    level: "Beginner",
    difficulty: "Easy",
    xp: 20,
    premium: false,
    description:
      "Write a function that checks whether a given string reads the same forwards and backwards, ignoring case. Return true or false.",
    examples: [
      { input: `"Madam"`, output: "true" },
      { input: `"hello"`, output: "false" },
    ],
    constraints: ["1 <= s.length <= 10^4"],
    functionName: "isPalindrome",
    starterCode: `function isPalindrome(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["Madam"], expected: true },
      { args: ["hello"], expected: false },
      { args: ["racecar"], expected: true },
      { args: ["Wasitacaroracat Isaw".replace(/\s/g, "")], expected: false },
    ],
    solution: `function isPalindrome(s) {\n  const normalized = s.toLowerCase();\n  const reversed = normalized.split("").reverse().join("");\n  return normalized === reversed;\n}`,
    explanation:
      "Normalize case first, then compare the string to its own reverse. Any mismatch means it isn't a palindrome.",
  },
  {
    id: "e4",
    title: "FizzBuzz",
    topic: "Loops & Conditionals",
    level: "Beginner",
    difficulty: "Easy",
    xp: 15,
    premium: false,
    description:
      "Write a function that takes a number n and returns an array of strings from 1 to n where: multiples of 3 are 'Fizz', multiples of 5 are 'Buzz', multiples of both are 'FizzBuzz', and everything else is the number itself as a string.",
    examples: [
      { input: "5", output: `["1","2","Fizz","4","Buzz"]` },
      { input: "15", output: "[...,'FizzBuzz'] at index 15" },
    ],
    constraints: ["1 <= n <= 10^4"],
    functionName: "fizzBuzz",
    starterCode: `function fizzBuzz(n) {\n  // your code here\n}`,
    testCases: [
      { args: [5], expected: ["1", "2", "Fizz", "4", "Buzz"] },
      {
        args: [15],
        expected: [
          "1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz",
          "11", "Fizz", "13", "14", "FizzBuzz",
        ],
      },
    ],
    solution: `function fizzBuzz(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) result.push("FizzBuzz");\n    else if (i % 3 === 0) result.push("Fizz");\n    else if (i % 5 === 0) result.push("Buzz");\n    else result.push(String(i));\n  }\n  return result;\n}`,
    explanation:
      "Check divisibility by 15 first (both 3 and 5) before checking 3 or 5 individually, otherwise 'Fizz' or 'Buzz' would be pushed instead of 'FizzBuzz'.",
  },
  {
    id: "e5",
    title: "Count Vowels",
    topic: "Strings",
    level: "Beginner",
    difficulty: "Easy",
    xp: 15,
    premium: false,
    description: "Write a function that counts how many vowels (a, e, i, o, u — case-insensitive) appear in a string.",
    examples: [
      { input: `"JavaScript"`, output: "3" },
      { input: `"rhythm"`, output: "0" },
    ],
    constraints: ["0 <= s.length <= 10^4"],
    functionName: "countVowels",
    starterCode: `function countVowels(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["JavaScript"], expected: 3 },
      { args: ["rhythm"], expected: 0 },
      { args: ["AEIOU"], expected: 5 },
      { args: [""], expected: 0 },
    ],
    solution: `function countVowels(s) {\n  const matches = s.match(/[aeiou]/gi);\n  return matches ? matches.length : 0;\n}`,
    explanation:
      "A case-insensitive regex matches all vowel characters at once; match() returns null (not an empty array) when there are no matches, so guard against that.",
  },
  {
    id: "e6",
    title: "Sum of Array Elements",
    topic: "Arrays",
    level: "Beginner",
    difficulty: "Easy",
    xp: 15,
    premium: false,
    description: "Write a function that returns the sum of all numbers in an array using reduce().",
    examples: [
      { input: "[1, 2, 3, 4]", output: "10" },
      { input: "[]", output: "0" },
    ],
    constraints: ["0 <= arr.length <= 10^5"],
    functionName: "sumArray",
    starterCode: `function sumArray(arr) {\n  // your code here — use reduce()\n}`,
    testCases: [
      { args: [[1, 2, 3, 4]], expected: 10 },
      { args: [[]], expected: 0 },
      { args: [[-5, 5]], expected: 0 },
      { args: [[100]], expected: 100 },
    ],
    solution: `function sumArray(arr) {\n  return arr.reduce((total, n) => total + n, 0);\n}`,
    explanation:
      "reduce() walks the array accumulating a running total, starting from 0 so it correctly returns 0 for an empty array.",
  },
  {
    id: "e7",
    title: "Remove Duplicates from an Array",
    topic: "Arrays",
    level: "Beginner",
    difficulty: "Easy",
    xp: 20,
    premium: false,
    description: "Write a function that removes duplicate values from an array and returns a new array with only unique values, preserving order.",
    examples: [
      { input: "[1, 2, 2, 3, 1]", output: "[1, 2, 3]" },
      { input: `["a","b","a"]`, output: `["a","b"]` },
    ],
    constraints: ["0 <= arr.length <= 10^5"],
    functionName: "uniqueArray",
    starterCode: `function uniqueArray(arr) {\n  // your code here\n}`,
    testCases: [
      { args: [[1, 2, 2, 3, 1]], expected: [1, 2, 3] },
      { args: [["a", "b", "a"]], expected: ["a", "b"] },
      { args: [[]], expected: [] },
    ],
    solution: `function uniqueArray(arr) {\n  return [...new Set(arr)];\n}`,
    explanation:
      "A Set automatically discards duplicate values while preserving insertion order; spreading it back into an array gives the deduplicated list.",
  },
  {
    id: "e8",
    title: "Capitalize Each Word",
    topic: "Strings",
    level: "Beginner",
    difficulty: "Easy",
    xp: 20,
    premium: false,
    description: "Write a function that capitalizes the first letter of every word in a sentence.",
    examples: [
      { input: `"the quick brown fox"`, output: `"The Quick Brown Fox"` },
    ],
    constraints: ["1 <= s.length <= 10^4"],
    functionName: "capitalizeWords",
    starterCode: `function capitalizeWords(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["the quick brown fox"], expected: "The Quick Brown Fox" },
      { args: ["hello"], expected: "Hello" },
    ],
    solution: `function capitalizeWords(s) {\n  return s\n    .split(" ")\n    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))\n    .join(" ");\n}`,
    explanation:
      "Split the sentence into words, uppercase just the first character of each word while keeping the rest as-is, then rejoin with spaces.",
  },

  // ============================================================
  // MEDIUM (8) — Intermediate
  // ============================================================
  {
    id: "m1",
    title: "Two Sum",
    topic: "Arrays & Hashing",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 40,
    premium: false,
    description:
      "Given an array of integers nums and a target integer, return the indices of the two numbers that add up to target. Assume exactly one solution exists and you can't use the same element twice.",
    examples: [
      { input: "nums=[2,7,11,15], target=9", output: "[0,1]" },
      { input: "nums=[3,2,4], target=6", output: "[1,2]" },
    ],
    constraints: ["2 <= nums.length <= 10^4", "A valid answer always exists"],
    functionName: "twoSum",
    starterCode: `function twoSum(nums, target) {\n  // your code here\n}`,
    testCases: [
      { args: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { args: [[3, 2, 4], 6], expected: [1, 2] },
      { args: [[3, 3], 6], expected: [0, 1] },
    ],
    solution: `function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (seen.has(complement)) return [seen.get(complement), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}`,
    explanation:
      "Instead of checking every pair (O(n^2)), store each number's index in a map as you go. For each number, check if its complement (target - num) was already seen — that gives O(n) time.",
  },
  {
    id: "m2",
    title: "Valid Parentheses",
    topic: "Stacks",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 40,
    premium: false,
    description:
      "Given a string containing just the characters (, ), {, }, [, ], determine if the input string is valid — every open bracket must be closed by the same type in the correct order.",
    examples: [
      { input: `"()[]{}"`, output: "true" },
      { input: `"(]"`, output: "false" },
    ],
    constraints: ["1 <= s.length <= 10^4"],
    functionName: "isValidParens",
    starterCode: `function isValidParens(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["()[]{}"], expected: true },
      { args: ["(]"], expected: false },
      { args: ["([{}])"], expected: true },
      { args: ["("], expected: false },
    ],
    solution: `function isValidParens(s) {\n  const pairs = { ")": "(", "]": "[", "}": "{" };\n  const stack = [];\n  for (const char of s) {\n    if (char === "(" || char === "[" || char === "{") {\n      stack.push(char);\n    } else {\n      if (stack.pop() !== pairs[char]) return false;\n    }\n  }\n  return stack.length === 0;\n}`,
    explanation:
      "Push opening brackets onto a stack. On a closing bracket, the top of the stack must be its matching opener — pop and compare. If the stack isn't empty at the end, something was never closed.",
  },
  {
    id: "m3",
    title: "Find the Missing Number",
    topic: "Math",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 35,
    premium: false,
    description:
      "Given an array containing n distinct numbers from 0 to n (inclusive), find the one number that's missing from the array.",
    examples: [
      { input: "[3,0,1]", output: "2" },
      { input: "[0,1]", output: "2" },
    ],
    constraints: ["n == arr.length", "0 <= arr.length <= 10^4"],
    functionName: "missingNumber",
    starterCode: `function missingNumber(arr) {\n  // your code here\n}`,
    testCases: [
      { args: [[3, 0, 1]], expected: 2 },
      { args: [[0, 1]], expected: 2 },
      { args: [[9, 6, 4, 2, 3, 5, 7, 0, 1]], expected: 8 },
    ],
    solution: `function missingNumber(arr) {\n  const n = arr.length;\n  const expectedSum = (n * (n + 1)) / 2;\n  const actualSum = arr.reduce((sum, x) => sum + x, 0);\n  return expectedSum - actualSum;\n}`,
    explanation:
      "The sum of 0..n has a known formula (n(n+1)/2). Subtracting the array's actual sum from that expected sum leaves exactly the missing number — O(n) time, O(1) space.",
  },
  {
    id: "m4",
    title: "First Non-Repeating Character",
    topic: "Strings & Hashing",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 35,
    premium: false,
    description:
      "Given a string, return the index of the first character that does not repeat anywhere else in the string. Return -1 if every character repeats.",
    examples: [
      { input: `"leetcode"`, output: "0" },
      { input: `"aabb"`, output: "-1" },
    ],
    constraints: ["1 <= s.length <= 10^5"],
    functionName: "firstUniqChar",
    starterCode: `function firstUniqChar(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["leetcode"], expected: 0 },
      { args: ["aabb"], expected: -1 },
      { args: ["loveleetcode"], expected: 2 },
    ],
    solution: `function firstUniqChar(s) {\n  const counts = {};\n  for (const char of s) counts[char] = (counts[char] || 0) + 1;\n  for (let i = 0; i < s.length; i++) {\n    if (counts[s[i]] === 1) return i;\n  }\n  return -1;\n}`,
    explanation:
      "First pass builds a frequency map of every character. Second pass walks the string in order and returns the first index whose count is exactly 1.",
  },
  {
    id: "m5",
    title: "Group Anagrams",
    topic: "Arrays & Hashing",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 45,
    premium: false,
    description:
      "Given an array of strings, group the anagrams together. Return an array of groups, each group being an array of the original strings.",
    examples: [
      { input: `["eat","tea","tan","ate","nat","bat"]`, output: `[["eat","tea","ate"],["tan","nat"],["bat"]]` },
    ],
    constraints: ["1 <= strs.length <= 10^4"],
    functionName: "groupAnagrams",
    starterCode: `function groupAnagrams(strs) {\n  // your code here\n}`,
    testCases: [
      {
        args: [["eat", "tea", "tan", "ate", "nat", "bat"]],
        expected: [["eat", "tea", "ate"], ["tan", "nat"], ["bat"]],
      },
    ],
    solution: `function groupAnagrams(strs) {\n  const groups = new Map();\n  for (const str of strs) {\n    const key = str.split("").sort().join("");\n    if (!groups.has(key)) groups.set(key, []);\n    groups.get(key).push(str);\n  }\n  return [...groups.values()];\n}`,
    explanation:
      "Anagrams share the same letters, so sorting each string's characters produces an identical 'key' for every anagram. Group strings in a map keyed by that sorted string.",
  },
  {
    id: "m6",
    title: "Flatten a Nested Array",
    topic: "Recursion",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 35,
    premium: false,
    description: "Write a function that flattens an arbitrarily nested array into a single flat array, without using the built-in Array.prototype.flat().",
    examples: [
      { input: "[1,[2,3],[4,[5,6]]]", output: "[1,2,3,4,5,6]" },
    ],
    constraints: ["Array can be nested to any depth"],
    functionName: "flattenArray",
    starterCode: `function flattenArray(arr) {\n  // your code here — no Array.prototype.flat()\n}`,
    testCases: [
      { args: [[1, [2, 3], [4, [5, 6]]]], expected: [1, 2, 3, 4, 5, 6] },
      { args: [[1, [2, [3, [4, [5]]]]]], expected: [1, 2, 3, 4, 5] },
      { args: [[]], expected: [] },
    ],
    solution: `function flattenArray(arr) {\n  let result = [];\n  for (const item of arr) {\n    if (Array.isArray(item)) {\n      result = result.concat(flattenArray(item));\n    } else {\n      result.push(item);\n    }\n  }\n  return result;\n}`,
    explanation:
      "Recursively walk each element: if it's an array, flatten it first and merge the result in; otherwise push the value directly. The recursion naturally handles any depth.",
  },
  {
    id: "m7",
    title: "Implement Array.prototype.map",
    topic: "Higher-order functions",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 40,
    premium: false,
    description: "Implement your own version of map — a function myMap(arr, callback) that returns a new array with callback applied to every element, without using the built-in .map().",
    examples: [
      { input: "myMap([1,2,3], x => x * 2)", output: "[2,4,6]" },
    ],
    constraints: ["callback receives (value, index, array)"],
    functionName: "myMap",
    starterCode: `function myMap(arr, callback) {\n  // your code here — no Array.prototype.map()\n}`,
    testCases: [
      { args: [[1, 2, 3], (x) => x * 2], expected: [2, 4, 6] },
      { args: [[1, 2, 3], (x, i) => x + i], expected: [1, 3, 5] },
      { args: [[], (x) => x], expected: [] },
    ],
    solution: `function myMap(arr, callback) {\n  const result = [];\n  for (let i = 0; i < arr.length; i++) {\n    result.push(callback(arr[i], i, arr));\n  }\n  return result;\n}`,
    explanation:
      "Loop through the array manually, call the callback with (value, index, array) just like the real map does, and collect the results in a new array.",
  },
  {
    id: "m8",
    title: "Chunk an Array",
    topic: "Arrays",
    level: "Intermediate",
    difficulty: "Medium",
    xp: 35,
    premium: false,
    description: "Write a function that splits an array into chunks (sub-arrays) of a given size. The last chunk may have fewer elements.",
    examples: [
      { input: "chunk([1,2,3,4,5], 2)", output: "[[1,2],[3,4],[5]]" },
    ],
    constraints: ["1 <= size"],
    functionName: "chunkArray",
    starterCode: `function chunkArray(arr, size) {\n  // your code here\n}`,
    testCases: [
      { args: [[1, 2, 3, 4, 5], 2], expected: [[1, 2], [3, 4], [5]] },
      { args: [[1, 2, 3, 4], 4], expected: [[1, 2, 3, 4]] },
      { args: [[], 3], expected: [] },
    ],
    solution: `function chunkArray(arr, size) {\n  const chunks = [];\n  for (let i = 0; i < arr.length; i += size) {\n    chunks.push(arr.slice(i, i + size));\n  }\n  return chunks;\n}`,
    explanation:
      "Step through the array size elements at a time, slicing out each chunk. slice() naturally handles the shorter final chunk without extra checks.",
  },

  // ============================================================
  // HARD (10) — Advanced (premium locked)
  // ============================================================
  {
    id: "h1",
    title: "Longest Substring Without Repeating Characters",
    topic: "Sliding Window",
    level: "Advanced",
    difficulty: "Hard",
    xp: 70,
    premium: true,
    description: "Given a string, find the length of the longest substring without repeating characters.",
    examples: [
      { input: `"abcabcbb"`, output: "3 (\"abc\")" },
      { input: `"bbbbb"`, output: "1" },
    ],
    constraints: ["0 <= s.length <= 5*10^4"],
    functionName: "lengthOfLongestSubstring",
    starterCode: `function lengthOfLongestSubstring(s) {\n  // your code here\n}`,
    testCases: [
      { args: ["abcabcbb"], expected: 3 },
      { args: ["bbbbb"], expected: 1 },
      { args: ["pwwkew"], expected: 3 },
      { args: [""], expected: 0 },
    ],
    solution: `function lengthOfLongestSubstring(s) {\n  const seen = new Map();\n  let start = 0;\n  let maxLen = 0;\n  for (let end = 0; end < s.length; end++) {\n    const char = s[end];\n    if (seen.has(char) && seen.get(char) >= start) {\n      start = seen.get(char) + 1;\n    }\n    seen.set(char, end);\n    maxLen = Math.max(maxLen, end - start + 1);\n  }\n  return maxLen;\n}`,
    explanation:
      "Sliding window: expand 'end' one character at a time. If that character was already seen inside the current window, jump 'start' past its last occurrence. Track the max window size as you go — O(n) time.",
  },
  {
    id: "h2",
    title: "Merge Overlapping Intervals",
    topic: "Intervals",
    level: "Advanced",
    difficulty: "Hard",
    xp: 65,
    premium: true,
    description: "Given an array of intervals [start, end], merge all overlapping intervals and return the merged, non-overlapping intervals sorted by start.",
    examples: [
      { input: "[[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]" },
    ],
    constraints: ["1 <= intervals.length <= 10^4"],
    functionName: "mergeIntervals",
    starterCode: `function mergeIntervals(intervals) {\n  // your code here\n}`,
    testCases: [
      {
        args: [[[1, 3], [2, 6], [8, 10], [15, 18]]],
        expected: [[1, 6], [8, 10], [15, 18]],
      },
      { args: [[[1, 4], [4, 5]]], expected: [[1, 5]] },
    ],
    solution: `function mergeIntervals(intervals) {\n  const sorted = [...intervals].sort((a, b) => a[0] - b[0]);\n  const result = [sorted[0]];\n  for (let i = 1; i < sorted.length; i++) {\n    const last = result[result.length - 1];\n    const current = sorted[i];\n    if (current[0] <= last[1]) {\n      last[1] = Math.max(last[1], current[1]);\n    } else {\n      result.push(current);\n    }\n  }\n  return result;\n}`,
    explanation:
      "Sort intervals by start time first. Then walk through them, merging into the last result interval whenever the current interval's start is within (or touches) the last one's end.",
  },
  {
    id: "h3",
    title: "Deep Clone a Nested Object",
    topic: "Recursion",
    level: "Advanced",
    difficulty: "Hard",
    xp: 60,
    premium: true,
    description: "Implement a deepClone function that creates a full deep copy of a nested object/array structure, without using JSON.parse(JSON.stringify(...)) or structuredClone().",
    examples: [
      { input: "{ a: 1, b: { c: [1,2,3] } }", output: "an independent deep copy" },
    ],
    constraints: ["Handles nested objects and arrays"],
    functionName: "deepClone",
    starterCode: `function deepClone(value) {\n  // your code here — no JSON.stringify/parse, no structuredClone\n}`,
    testCases: [
      {
        args: [{ a: 1, b: { c: [1, 2, 3] } }],
        expected: { a: 1, b: { c: [1, 2, 3] } },
      },
      { args: [[1, [2, [3, 4]]]], expected: [1, [2, [3, 4]]] },
    ],
    solution: `function deepClone(value) {\n  if (value === null || typeof value !== "object") return value;\n  if (Array.isArray(value)) return value.map((item) => deepClone(item));\n  const result = {};\n  for (const key in value) {\n    if (Object.prototype.hasOwnProperty.call(value, key)) {\n      result[key] = deepClone(value[key]);\n    }\n  }\n  return result;\n}`,
    explanation:
      "Primitives are returned as-is. Arrays and objects are rebuilt from scratch, recursively cloning every nested value so the copy shares no references with the original.",
  },
  {
    id: "h4",
    title: "Implement a Curry Function",
    topic: "Functional Programming",
    level: "Advanced",
    difficulty: "Hard",
    xp: 70,
    premium: true,
    description: "Implement curry(fn) that transforms a function so it can be called with arguments one at a time: curry(add)(1)(2)(3) should behave the same as add(1,2,3). This is graded by self-check here since calling pattern varies.",
    examples: [
      { input: "curry((a,b,c) => a+b+c)(1)(2)(3)", output: "6" },
    ],
    constraints: ["Works for functions with any fixed number of arguments"],
    functionName: "curry",
    starterCode: `function curry(fn) {\n  // your code here — return a curried version of fn\n}`,
    testCases: null,
    solution: `function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) {\n      return fn.apply(this, args);\n    }\n    return (...next) => curried.apply(this, [...args, ...next]);\n  };\n}`,
    explanation:
      "fn.length tells you how many arguments the original function expects. Keep collecting arguments across calls; once enough have been gathered, invoke the original function with all of them.",
  },
  {
    id: "h5",
    title: "Median of Two Sorted Arrays",
    topic: "Binary Search",
    level: "Advanced",
    difficulty: "Hard",
    xp: 90,
    premium: true,
    description: "Given two sorted arrays, find the median of the two combined arrays. Aim for better than O((m+n) log(m+n)) if possible, but a correct O(m+n) merge-based solution is also accepted here.",
    examples: [
      { input: "[1,3], [2]", output: "2" },
      { input: "[1,2], [3,4]", output: "2.5" },
    ],
    constraints: ["Combined arrays are never empty"],
    functionName: "findMedianSortedArrays",
    starterCode: `function findMedianSortedArrays(nums1, nums2) {\n  // your code here\n}`,
    testCases: [
      { args: [[1, 3], [2]], expected: 2 },
      { args: [[1, 2], [3, 4]], expected: 2.5 },
      { args: [[], [1]], expected: 1 },
    ],
    solution: `function findMedianSortedArrays(nums1, nums2) {\n  const merged = [...nums1, ...nums2].sort((a, b) => a - b);\n  const mid = Math.floor(merged.length / 2);\n  if (merged.length % 2 === 0) {\n    return (merged[mid - 1] + merged[mid]) / 2;\n  }\n  return merged[mid];\n}`,
    explanation:
      "A straightforward correct approach merges and sorts both arrays, then picks the middle element (or averages the two middle elements for an even-length array). The true O(log(min(m,n))) binary-search solution partitions both arrays without fully merging them — worth researching once this version works.",
  },
  {
    id: "h6",
    title: "Implement Array.prototype.reduce",
    topic: "Higher-order functions",
    level: "Advanced",
    difficulty: "Hard",
    xp: 65,
    premium: true,
    description: "Implement your own version of reduce — myReduce(arr, callback, initialValue) — without using the built-in .reduce().",
    examples: [
      { input: "myReduce([1,2,3,4], (acc,x) => acc+x, 0)", output: "10" },
    ],
    constraints: ["Should work with or without an initial value provided"],
    functionName: "myReduce",
    starterCode: `function myReduce(arr, callback, initialValue) {\n  // your code here — no Array.prototype.reduce()\n}`,
    testCases: [
      { args: [[1, 2, 3, 4], (acc, x) => acc + x, 0], expected: 10 },
      { args: [[1, 2, 3], (acc, x) => acc * x, 1], expected: 6 },
    ],
    solution: `function myReduce(arr, callback, initialValue) {\n  let acc = initialValue !== undefined ? initialValue : arr[0];\n  const startIndex = initialValue !== undefined ? 0 : 1;\n  for (let i = startIndex; i < arr.length; i++) {\n    acc = callback(acc, arr[i], i, arr);\n  }\n  return acc;\n}`,
    explanation:
      "If no initial value is given, the first element becomes the starting accumulator and the loop starts from index 1 (matching native reduce's behavior). Otherwise start from index 0 with the given initial value.",
  },
  {
    id: "h7",
    title: "Serialize an Object into a Query String",
    topic: "Objects & Strings",
    level: "Advanced",
    difficulty: "Hard",
    xp: 60,
    premium: true,
    description: "Write a function that converts a flat object into a URL query string, properly encoding keys and values.",
    examples: [
      { input: `{ search: "js code", page: 2 }`, output: `"search=js%20code&page=2"` },
    ],
    constraints: ["Object has only string/number values (flat, no nesting)"],
    functionName: "toQueryString",
    starterCode: `function toQueryString(obj) {\n  // your code here\n}`,
    testCases: [
      { args: [{ search: "js code", page: 2 }], expected: "search=js%20code&page=2" },
      { args: [{ a: 1 }], expected: "a=1" },
    ],
    solution: `function toQueryString(obj) {\n  return Object.entries(obj)\n    .map(([key, value]) => \`\${encodeURIComponent(key)}=\${encodeURIComponent(value)}\`)\n    .join("&");\n}`,
    explanation:
      "Object.entries turns the object into [key, value] pairs. Each pair is URL-encoded individually with encodeURIComponent, then joined with '&' to build the final query string.",
  },
  {
    id: "h8",
    title: "Implement a Debounce Function",
    topic: "Timing & Closures",
    level: "Advanced",
    difficulty: "Hard",
    xp: 70,
    premium: true,
    description:
      "Implement debounce(fn, delay) that returns a debounced version of fn — calling it repeatedly resets a timer, and fn only actually runs once no calls have happened for 'delay' milliseconds. This is timing-based, so it's graded by self-check rather than automated tests here.",
    examples: [
      { input: "debounce(save, 300) called 5x quickly", output: "save() runs only once, 300ms after the last call" },
    ],
    constraints: ["Should preserve `this` and pass through arguments to fn"],
    functionName: "debounce",
    starterCode: `function debounce(fn, delay) {\n  // your code here\n}`,
    testCases: null,
    solution: `function debounce(fn, delay) {\n  let timeoutId;\n  return function (...args) {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => fn.apply(this, args), delay);\n  };\n}`,
    explanation:
      "Each call clears any pending timer and starts a new one. Only when 'delay' ms pass without another call does the timer finally fire and run the original function — that's what makes it 'debounced'.",
  },
  {
    id: "h9",
    title: "Build a Simple Event Emitter",
    topic: "Design Patterns",
    level: "Advanced",
    difficulty: "Hard",
    xp: 80,
    premium: true,
    description:
      "Implement a class EventEmitter with on(event, callback), off(event, callback), and emit(event, ...args) methods — the core building block behind pub/sub systems and Node's EventEmitter. This is stateful/class-based, so it's graded by self-check rather than automated tests here.",
    examples: [
      { input: "emitter.on('msg', cb); emitter.emit('msg', 'hi')", output: "cb('hi') is called" },
    ],
    constraints: ["emit should call every listener registered for that event, in order"],
    functionName: "EventEmitter",
    starterCode: `class EventEmitter {\n  constructor() {\n    this.events = {};\n  }\n\n  on(event, callback) {\n    // your code here\n  }\n\n  off(event, callback) {\n    // your code here\n  }\n\n  emit(event, ...args) {\n    // your code here\n  }\n}`,
    testCases: null,
    solution: `class EventEmitter {\n  constructor() {\n    this.events = {};\n  }\n\n  on(event, callback) {\n    if (!this.events[event]) this.events[event] = [];\n    this.events[event].push(callback);\n  }\n\n  off(event, callback) {\n    if (!this.events[event]) return;\n    this.events[event] = this.events[event].filter((cb) => cb !== callback);\n  }\n\n  emit(event, ...args) {\n    if (!this.events[event]) return;\n    this.events[event].forEach((callback) => callback(...args));\n  }\n}`,
    explanation:
      "Internally store listeners in an object keyed by event name, each holding an array of callbacks. on() pushes to that array, off() filters the callback out, and emit() calls every remaining listener with the passed arguments.",
  },
  {
    id: "h10",
    title: "Implement Promise.all from Scratch",
    topic: "Async & Promises",
    level: "Advanced",
    difficulty: "Hard",
    xp: 90,
    premium: true,
    description:
      "Implement myPromiseAll(promises) that behaves like Promise.all — it resolves with an array of all resolved values (in original order) once every promise resolves, or rejects immediately if any promise rejects. This is async/timing-based, so it's graded by self-check rather than automated tests here.",
    examples: [
      { input: "myPromiseAll([p1, p2, p3])", output: "resolves with [v1, v2, v3] once all resolve" },
    ],
    constraints: ["Should reject as soon as any single promise rejects"],
    functionName: "myPromiseAll",
    starterCode: `function myPromiseAll(promises) {\n  // your code here — return a Promise\n}`,
    testCases: null,
    solution: `function myPromiseAll(promises) {\n  return new Promise((resolve, reject) => {\n    const results = new Array(promises.length);\n    let completed = 0;\n\n    if (promises.length === 0) return resolve(results);\n\n    promises.forEach((p, index) => {\n      Promise.resolve(p)\n        .then((value) => {\n          results[index] = value;\n          completed++;\n          if (completed === promises.length) resolve(results);\n        })\n        .catch(reject);\n    });\n  });\n}`,
    explanation:
      "Wrap each promise so its resolved value is stored at its original index (not push order, since they can resolve out of order). Track how many have completed; resolve once all are done, or reject immediately on the first failure.",
  },
];

export default codingTasks;